token: "XXXXXXXXXXXXXXXXXXX"

engines:
  bullet:
    dir: "./engines"
    name: "stockfish"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 22.5
    uci_options:
      Threads: 8
      Hash: 5800
      Move Overhead: 100
    limits:

  chess960:
    dir: "./engines"
    name: "stockfish"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 20.0
    uci_options:
      Threads: 8
      Hash: 4096
      Move Overhead: 100
    limits:

  standard:
    dir: "./engines"
    name: "stockfish"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 23.0
    uci_options:
      Threads: 8
      Hash: 8192
      Move Overhead: 100
    limits:

  variants:
    dir: "./engines"
    name: "stockfish"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 1.0
    uci_options:
      Threads: 8
      Hash: 4096
      Move Overhead: 100
    limits:

syzygy:
  standard:
    enabled: true
    paths:
      - "./syzygy"
    max_pieces: 7
    instant_play: true
  chess960:
    enabled: true
    paths:
      - "./syzygy"
    max_pieces: 7
    instant_play: true

gaviota:
  enabled: false
  paths:
    - "/path/to/gaviota"
  max_pieces: 5

opening_books:
  enabled: true
  priority: 400
  read_learn: false
  books:
    0.5+0_white:
      selection: weighted_random
      max_depth: 20
      names:
        - nimas
    0.5+0_black:
      selection: best_move
      names:
        - lowpro
        - probook
    bullet_white:
      selection: weighted_random
      max_depth: 20
      names:
        - small
        - probook
    bullet_black:
      selection: best_move
      max_depth: 15
      names:
        - small
        - probook
    3+0:
      selection: weighted_random
      names:
        - small
        - probook
    standard:
      selection: weighted_random
      names:
        - small
    chess960:
      selection: best_move
      names:
        - chess960
    standard_human:
      selection: weighted_random
      random_selection: true
      names:
        - Nakamura
        - Carlsen
        - Caruana
        - Ding
        - Gukesh
    bullet_human:
      selection: weighted_random
      random_selection: true
      names:
        - Kasparov
        - Carlsen
        - Caruana
        - Ding
        - Gukesh
        - Nakamura
        - Nepomniachtchi
    blitz_human:
      selection: weighted_random
      random_selection: true
      names:
        - Nakamura
        - Carlsen
        - Nepomniachtchi
    rapid_human:
      selection: best_move
      random_selection: true
      names:
        - Kasparov
        - Carlsen
        - Caruana
        - Ding
        - Gukesh
        - Nakamura
        - Nepomniachtchi

online_moves:
  opening_explorer:
    enabled: false
    priority: 300
    only_without_book: false
    use_for_variants: false
    min_time: 10
    timeout: 5
    min_games: 5
    only_with_wins: false
    selection: "performance"
    anti: false
  lichess_cloud:
    enabled: false
    priority: 200
    only_without_book: false
    use_for_variants: false
    min_eval_depth: 10
    min_time: 10
    timeout: 5
  chessdb:
    enabled: false
    priority: 100
    only_without_book: false
    min_candidates: 1
    min_time: 10
    timeout: 5
    selection: "best"
  online_egtb:
    enabled: true
    min_time: 20
    timeout: 3

offer_draw:
  enabled: true
  score: 10
  consecutive_moves: 5
  min_game_length: 25
  against_humans: false
  allow_in_tournaments: true
  accept_30_second_draws: true

resign:
  enabled: true
  score: -800
  consecutive_moves: 8
  against_humans: false

rematch:
  enabled: false
  max_consecutive: 3
  offer_on_win: true
  offer_on_loss: true
  offer_on_draw: true
  against_humans: false
  against_bots: true
  delay_seconds: 1
  timeout_seconds: 30

challenge:
  concurrency: 1
  max_takebacks: 3
  bullet_with_increment_only: false
  min_rating_diff: 0
  max_rating_diff: 300
  variant_rating_diffs:
    standard:
      max: 200
    chess960:
      max: 350
  variants:
    - standard
    - chess960
    - fromPosition
  time_controls:
    - bullet
    - blitz
    - rapid
    - 25+0
  bot_modes:
    - casual
    - rated
  human_modes:
    - casual
    - rated

matchmaking:
  delay: 120
  allow_matchmaking: true
  challenge_mode: rated
  timeout: 30
  selection: weighted_random
  types:
    bullet_0_5:
      enabled: true
      tc: "0.5+0"
      variant: standard
    blitz_3_0:
      enabled: true
      tc: "3+0"
      variant: standard
    rapid_8+0:
      enabled: true
      tc: "8+0"
      variant: standard
    0.5_chess960:
      enabled: true
      tc: "0.5+0"
      variant: chess960

messages:
  greeting: "Hello {opponent}! Good luck and have fun! Type !help for a list of commands."
  goodbye: "Thank you for the game, {opponent}!"
  greeting_spectators: "Welcome spectators! Type !help for a list of commands."
  goodbye_spectators: "Thank you all for watching!"

whitelist:

blacklist:

books:
  Kasparov: "./masterbooks/Kasparov.bin"
  Carlsen: "./masterbooks/Carlsen.bin"
  Caruana: "./masterbooks/Caruana.bin"
  Ding: "./masterbooks/Ding.bin"
  Gukesh: "./masterbooks/Gukesh.bin"
  Nakamura: "./masterbooks/Nakamura.bin"
  Nepomniachtchi: "./masterbooks/Nepomniachtchi.bin"
  lowpro: "./books/lowpro.bin"
  probook: "./books/probook.bin"
  chess960: "./books/chess960.bin"
  small: "./books/small.bin"
  nimas: "./books/nimas.bin"
